name: nomina
version: "1.0.0"
profile: nomina

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

flags:
  send_anonymous_usage_stats: false

models:
  nomina:
    staging:
      +schema: staging
      +materialized: view
